# Generated by Django 3.2.6 on 2023-09-26 15:15

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_balance_balancetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=256),
        ),
        migrations.AlterField(
            model_name='balancetransaction',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=256),
        ),
        migrations.AlterField(
            model_name='flavorprice',
            name='hourly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=256),
        ),
        migrations.AlterField(
            model_name='flavorprice',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=256, null=True),
        ),
        migrations.AlterField(
            model_name='floatingipsprice',
            name='hourly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=256),
        ),
        migrations.AlterField(
            model_name='floatingipsprice',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=256, null=True),
        ),
        migrations.AlterField(
            model_name='imageprice',
            name='hourly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=256),
        ),
        migrations.AlterField(
            model_name='imageprice',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=256, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=256, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=256, null=True),
        ),
        migrations.AlterField(
            model_name='invoicefloatingip',
            name='hourly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=256),
        ),
        migrations.AlterField(
            model_name='invoicefloatingip',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=256, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceimage',
            name='hourly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=256),
        ),
        migrations.AlterField(
            model_name='invoiceimage',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=256, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceinstance',
            name='hourly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=256),
        ),
        migrations.AlterField(
            model_name='invoiceinstance',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=256, null=True),
        ),
        migrations.AlterField(
            model_name='invoicerouter',
            name='hourly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=256),
        ),
        migrations.AlterField(
            model_name='invoicerouter',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=256, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesnapshot',
            name='hourly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=256),
        ),
        migrations.AlterField(
            model_name='invoicesnapshot',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=256, null=True),
        ),
        migrations.AlterField(
            model_name='invoicevolume',
            name='hourly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=256),
        ),
        migrations.AlterField(
            model_name='invoicevolume',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=256, null=True),
        ),
        migrations.AlterField(
            model_name='routerprice',
            name='hourly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=256),
        ),
        migrations.AlterField(
            model_name='routerprice',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=256, null=True),
        ),
        migrations.AlterField(
            model_name='snapshotprice',
            name='hourly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=256),
        ),
        migrations.AlterField(
            model_name='snapshotprice',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=256, null=True),
        ),
        migrations.AlterField(
            model_name='volumeprice',
            name='hourly_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=256),
        ),
        migrations.AlterField(
            model_name='volumeprice',
            name='monthly_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=256, null=True),
        ),
    ]
